<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-28 21:20

$extensionPath = t3lib_extMgm::extPath('feusermanagement');
return array(
	'tx_feusermanagement_field' => $extensionPath . 'class.Field.php',
	'tx_feusermanagement_model' => $extensionPath . 'class.registration_model.php',
	'tx_feusermanagement_validation' => $extensionPath . 'class.registration_validation.php',
	'tx_feusermanagement_view' => $extensionPath . 'class.registration_view.php',
	'tx_feusermanagement_pibase' => $extensionPath . 'lib/class.tx_feusermanagement_pibase.php',
	'tx_feusermanagement_mailer' => $extensionPath . 'lib/class.tx_feusermanagement_mailer.php',
);
?>